### ISSUE TITLE
Some datasets are split in two?

### ISSUE THREAD

**Issue by arielsegura** [nahuelhds/votaciones-diputados-argentina#3]
There are some files that have been split into two files for some reason, why is that? 

![image](https://user-images.githubusercontent.com/12116053/56498337-85763500-6501-11e9-936c-1f1a34b36609.png)

It may be good to document this or fix it if it's a bug.

**Comment by nahuelhds** [comment]
Resolved in #4

**Comment by nahuelhds** [comment]
Resolved in #4
