### ISSUE TITLE
Los CSVs de diputados estan rotos?

### ISSUE THREAD

**Issue by arielsegura** [nahuelhds/votaciones-diputados-argentina#9]
Estuve trabajando con una copia local de los datasets y cuando los volvi a descargar me dejo de funcionar todo. 

El error que tengo al cargarlos con pandas es el siguiente:
```
ParserError: Error tokenizing data. C error: Expected 8 fields in line 258, saw 15
```

En el CSV linea 258 al final de las columnas aparece nuevamente el header:

```csv
"2008-11-26 18:11:36",2032,"ZAVALLO, Gustavo Marcelo","Frente para la Victoria - PJ","Entre Ríos","AFIRMATIVO","https://votaciones.hcdn.gob.ar/public/diputados/images/A4603.jpg","date","votingId","legislator","party","region","vote","photoUrl","videoUrl"
```

Lo puedo arreglar a mano de mi lado pero estaria bueno arreglarlo en el generador de datasets asi nadie mas tiene este problema.

**Comment by arielsegura** [comment]
El file es votaciones_diputados_2008

**Comment by nahuelhds** [comment]
Genial Ari. Lo voy a revisar. Por lo pronto te recomiendo apuntar a alguno de los releases generados. Los hice pensando en poder apuntar hacia atrás y no dejar colgado a nadie con cada mejora implementada (como en este caso)

**Comment by nahuelhds** [comment]
Fíjate con la 0.1 o la 0.2. En la 0.3 resubí todo Diputados con mejores datos pero tal como se descarga desde el scrapper y sin normalizar.

Fíjate por acá
https://github.com/nahuelhds/votaciones-ar-datasets/releases

**Comment by nahuelhds** [comment]
@arielsegura ahí quité todos los encabezados repetidos de **todos** los datasets de formato CSV
